version: '3.8'
services:
    php8-sf6:
        container_name: php-sf
        build: php-sf
        ports:
            - "9080:8000"
        volumes:
            - ./project:/var/www/html

    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
networks:
    dev:

volumes:
  db-data:
